### ISSUE TITLE
Reading in Source Column and Adding to SBOL

### ISSUE THREAD

**Issue by JMante1** [SynBioHub/Plugin-Submit-Excel-Library#5]
# Clarify Source Column
Currently there is confusion between the source column and whether that is an organism or a derived from or a citation. Clarify what goes in the column and perhaps create more columns in the template.

# Citations
Be able to process citations and add them to SBOL. Decide how they should be added to sbol (pubmed id tag, prov:derived from tag, etc).

Example for things currently found in the source column:

PMID:   24295448
pRU1701
GenBank: J01830.1
http://parts.igem.org/Part:BBa_K174004
https://link.springer.com/protocol/10.1007/978-1-4939-0473-0_36

**Comment by jakebeal** [comment]
Migrated to shared library: https://github.com/SynBioDex/Excel-to-SBOL/issues/1
